name: Publish Image Docker

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'
      tags:
        description: 'Tags'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        export tag=$(git rev-parse --short "$GITHUB_SHA")
        export actor=pyriemann
        docker build . --file Dockerfile --tag ghcr.io/${actor}/pyriemann-qiskit:$tag
    - name: Publish the Docker image
      run: |
        export tag=$(git rev-parse --short "$GITHUB_SHA")
        export actor=pyriemann
        docker login ghcr.io -u ${actor} -p $GITHUB_TOKEN
        docker push ghcr.io/${actor}/pyriemann-qiskit:$tag
